INSERT INTO general.measure_units (abbreviation) VALUES
    ('Ml'),
    ('Cl'),
    ('L'),
    ('Oz'),
    ('Drop'),
    ('Tsp'),
    ('Tbsp'),
    ('Dash'),
    ('Splash'),
    ('G'),
    ('Kg'),
    ('Mg'),
    ('Lb'),
    ('OzWt'),
    ('Ton'),
    ('Pcs'),
    ('Leaf'),
    ('Clove'),
    ('Stick'),
    ('Pinch'),
    ('Ms'),
    ('Bunch')
    ON CONFLICT (abbreviation) DO NOTHING;